package theme

import "github.com/charmbracelet/lipgloss"

var ThemeCatalog = map[string]*Theme{
	"default_dark": {
		Name:       "Default Dark",
		Background: lipgloss.Color("#1e1e2e"),
		Foreground: lipgloss.Color("#cdd6f4"),
		Sub:        lipgloss.Color("#585b70"),
		Main:       lipgloss.Color("#89b4fa"),
		Caret:      lipgloss.Color("#89b4fa"),
		Correct:    lipgloss.Color("#a6e3a1"),
		Error:      lipgloss.Color("#f38ba8"),
		ExtraError: lipgloss.Color("#7c2f3e"),
	},
	"dracula": {
		Name:       "Dracula",
		Background: lipgloss.Color("#282a36"),
		Foreground: lipgloss.Color("#f8f8f2"),
		Sub:        lipgloss.Color("#6272a4"),
		Main:       lipgloss.Color("#bd93f9"),
		Caret:      lipgloss.Color("#ff79c6"),
		Correct:    lipgloss.Color("#50fa7b"),
		Error:      lipgloss.Color("#ff5555"),
		ExtraError: lipgloss.Color("#7c2020"),
	},
	"nord": {
		Name:       "Nord",
		Background: lipgloss.Color("#2e3440"),
		Foreground: lipgloss.Color("#d8dee9"),
		Sub:        lipgloss.Color("#4c566a"),
		Main:       lipgloss.Color("#88c0d0"),
		Caret:      lipgloss.Color("#81a1c1"),
		Correct:    lipgloss.Color("#a3be8c"),
		Error:      lipgloss.Color("#bf616a"),
		ExtraError: lipgloss.Color("#6b2e33"),
	},
	"gruvbox_dark": {
		Name:       "Gruvbox Dark",
		Background: lipgloss.Color("#282828"),
		Foreground: lipgloss.Color("#ebdbb2"),
		Sub:        lipgloss.Color("#665c54"),
		Main:       lipgloss.Color("#fabd2f"),
		Caret:      lipgloss.Color("#fe8019"),
		Correct:    lipgloss.Color("#b8bb26"),
		Error:      lipgloss.Color("#fb4934"),
		ExtraError: lipgloss.Color("#7c2020"),
	},
	"catppuccin_mocha": {
		Name:       "Catppuccin Mocha",
		Background: lipgloss.Color("#1e1e2e"),
		Foreground: lipgloss.Color("#cdd6f4"),
		Sub:        lipgloss.Color("#585b70"),
		Main:       lipgloss.Color("#cba6f7"),
		Caret:      lipgloss.Color("#f5c2e7"),
		Correct:    lipgloss.Color("#a6e3a1"),
		Error:      lipgloss.Color("#f38ba8"),
		ExtraError: lipgloss.Color("#7c2f3e"),
	},
	"solarized_dark": {
		Name:       "Solarized Dark",
		Background: lipgloss.Color("#002b36"),
		Foreground: lipgloss.Color("#839496"),
		Sub:        lipgloss.Color("#586e75"),
		Main:       lipgloss.Color("#2aa198"),
		Caret:      lipgloss.Color("#cb4b16"),
		Correct:    lipgloss.Color("#859900"),
		Error:      lipgloss.Color("#dc322f"),
		ExtraError: lipgloss.Color("#7c1a18"),
	},
	"tokyo_night": {
		Name:       "Tokyo Night",
		Background: lipgloss.Color("#1a1b26"),
		Foreground: lipgloss.Color("#a9b1d6"),
		Sub:        lipgloss.Color("#565f89"),
		Main:       lipgloss.Color("#7aa2f7"),
		Caret:      lipgloss.Color("#bb9af7"),
		Correct:    lipgloss.Color("#9ece6a"),
		Error:      lipgloss.Color("#f7768e"),
		ExtraError: lipgloss.Color("#7c2f3e"),
	},
	"one_dark": {
		Name:       "One Dark",
		Background: lipgloss.Color("#282c34"),
		Foreground: lipgloss.Color("#abb2bf"),
		Sub:        lipgloss.Color("#5c6370"),
		Main:       lipgloss.Color("#61afef"),
		Caret:      lipgloss.Color("#c678dd"),
		Correct:    lipgloss.Color("#98c379"),
		Error:      lipgloss.Color("#e06c75"),
		ExtraError: lipgloss.Color("#7c2f3e"),
	},
	"rose_pine": {
		Name:       "Rose Pine",
		Background: lipgloss.Color("#191724"),
		Foreground: lipgloss.Color("#e0def4"),
		Sub:        lipgloss.Color("#6e6a86"),
		Main:       lipgloss.Color("#ebbcba"),
		Caret:      lipgloss.Color("#f6c177"),
		Correct:    lipgloss.Color("#9ccfd8"),
		Error:      lipgloss.Color("#eb6f92"),
		ExtraError: lipgloss.Color("#7c2f3e"),
	},
	"serika_dark": {
		Name:       "Serika Dark",
		Background: lipgloss.Color("#323437"),
		Foreground: lipgloss.Color("#d1d0c5"),
		Sub:        lipgloss.Color("#646669"),
		Main:       lipgloss.Color("#e2b714"),
		Caret:      lipgloss.Color("#e2b714"),
		Correct:    lipgloss.Color("#d1d0c5"),
		Error:      lipgloss.Color("#ca4754"),
		ExtraError: lipgloss.Color("#7e2a33"),
	},
}
